language: go
cache:
  directories:
    - $GOPATH/pkg/mod

go:
- 1.13.x

env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on

before_script:
- chmod +x test.sh

script:
- ./test.sh

after_success:
- bash <(curl -s https://codecov.io/bash)